require: rubocop-rspec
AllCops:
  Exclude:
    - 'config/**/*'
    - 'doc/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/factories.rb'
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/routes_spec.rb'
RSpec/DescribedClass:
  Exclude:
    - 'spec/requests/**/*'