source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.7.1'
gem 'pg'
gem 'rails_12factor', group: :production
gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'puma'
gem 'active_model_serializers', '~> 0.10.0'
gem 'kaminari'
gem 'rack-cors'
gem 'rspec_api_documentation'
gem 'apitome'
gem 'raddocs'
gem 'devise'
gem 'rails_admin'
gem 'database_cleaner'
gem 'slack-notifier'
gem 'paperclip'
gem 'aws-sdk', '~> 2.3'
gem 'jwt'
gem 'activerecord_json_validator'
gem 'validate_url'
gem 'generic_controller'
group :development do
  gem 'foreman'
  gem 'spring'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'guard'
  gem 'guard-bundler'
  gem 'rspec-rails', '~> 3.5'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'brakeman'
  gem 'bullet'
  gem 'json_matchers'
  gem 'stackprof'
  gem 'rack-mini-profiler'
  gem 'flamegraph'
end
